## 001_Scikit-Learn

In [6]:
import sklearn

print(sklearn.__version__)

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split


0.24.2


In [9]:
import pandas as pd

iris = load_iris()

# iris.data only has a numpy feature from Iris data set
iris_data = iris.data

# iris.target has a numpy label data from the iris data set
iris_label = iris.target
print('iris target: ', iris_label)
print('iris target name: ', iris.target_names)

# convert to the Dataframe
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)


iris target:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target name:  ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [10]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [16]:
# DecisionTreeClassifier
dt_clf = DecisionTreeClassifier(random_state=11)

# learning
dt_clf.fit(X_train, y_train)

# Predict from DecisionTreeClassifier object
pred = dt_clf.predict(X_test)

### Accuracy verification

In [17]:
from sklearn.metrics import accuracy_score
print('prediction accuracy: {0:.4f}'.format(accuracy_score(y_test, pred)))

prediction accuracy: 0.9333


## Part 2
Basic Framework of the scikit-learn

Estimator, fit(), predict()

In [1]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [2]:
keys = iris_data.keys()
print('keys of iris: ', keys)

keys of iris:  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [6]:
print('\n feature_names type: ', type(iris_data.feature_names))
print(' feature_names shape: ', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n targer_names type: ', type(iris_data.target_names))
print(' target_names shape: ', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data type: ', type(iris_data.data))
print(' data shape: ', iris_data.data.shape)
print(iris_data['data'])

print('\n target type: ', type(iris_data.target))
print(' target shape: ', iris_data.target.shape)
print(iris_data.target)


 feature_names type:  <class 'list'>
 feature_names shape:  4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 targer_names type:  <class 'numpy.ndarray'>
 target_names shape:  3
['setosa' 'versicolor' 'virginica']

 data type:  <class 'numpy.ndarray'>
 data shape:  (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5

## Train/Test set separation

In [12]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

iris = load_iris()
dt_clf = DecisionTreeClassifier()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

dt_clf.fit(X_train, y_train)

# prediction
pred = dt_clf.predict(X_test)
print('accuracy: {0:.4f}'.format(accuracy_score(y_test, pred)))

accuracy: 0.9556


In [13]:
from sklearn.model_selection import KFold
import numpy as np 

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# Separate 5 folds
kfold = KFold(n_splits=5)
cv_accuracy = []
print('size of the dataset: ', features.shape[0])

size of the dataset:  150


In [16]:
n_iter = 0

# KFold객체의 split()를 호출하면 fold 별 학습용, 검증용 테스트의 row index를 array로 반환
for train_index, test_index in kfold.split(features):
    #kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    # train and prediction
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter +=1
    # 반복 시마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도: {1}, train data size: {2}, verification data size: {3}'.format(n_iter, accuracy, train_size, test_index))
    print('#{0} verification set index: {1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
    # 개별 iteration별 정확도를 합하여 평균 정확도 계산
    print('\n## average verification accuracy: ', np.mean(cv_accuracy))


#1 교차 검증 정확도: 1.0, train data size: 120, verification data size: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
#1 verification set index: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

## average verification accuracy:  1.0

#2 교차 검증 정확도: 0.9667, train data size: 120, verification data size: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
#2 verification set index: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

## average verification accuracy:  0.98335

#3 교차 검증 정확도: 0.8667, train data size: 120, verification data size: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
#3 verification set index: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

## average verification accuracy:  0.9444666666666667

#4 교차 검증 정확도: 0.9

## Stratified K fold

In [17]:
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

c:\Users\JAMES\AppData\Local\Programs\Python\Python36\lib\importlib\_bootstrap.py:205: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
c:\Users\JAMES\AppData\Local\Programs\Python\Python36\lib\importlib\_bootstrap.py:205: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


2    50
1    50
0    50
Name: label, dtype: int64

In [19]:
kfold = KFold(n_splits=3)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## cross verification: {0}'.format(n_iter))
    print('train label data distibution:\n', label_train.value_counts())
    print('test label data distribution:\n', label_test.value_counts())

## cross verification: 1
train label data distibution:
 2    50
1    50
Name: label, dtype: int64
test label data distribution:
 0    50
Name: label, dtype: int64
## cross verification: 2
train label data distibution:
 2    50
0    50
Name: label, dtype: int64
test label data distribution:
 1    50
Name: label, dtype: int64
## cross verification: 3
train label data distibution:
 1    50
0    50
Name: label, dtype: int64
test label data distribution:
 2    50
Name: label, dtype: int64


In [20]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## cross verification: {0}'.format(n_iter))
    print('train label data distibution:\n', label_train.value_counts())
    print('test label data distribution:\n', label_test.value_counts())

## cross verification: 1
train label data distibution:
 2    34
1    33
0    33
Name: label, dtype: int64
test label data distribution:
 1    17
0    17
2    16
Name: label, dtype: int64
## cross verification: 2
train label data distibution:
 1    34
2    33
0    33
Name: label, dtype: int64
test label data distribution:
 2    17
0    17
1    16
Name: label, dtype: int64
## cross verification: 3
train label data distibution:
 0    34
2    33
1    33
Name: label, dtype: int64
test label data distribution:
 2    17
1    17
0    16
Name: label, dtype: int64


In [21]:
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

# StratifiedKFold의 split() 호출 시 반드시 label data set 추가 입력
for tarin_index, test_index in skfold.split(features, label):
    # split()으로 반환된 index를 이용해 train, validation test data extraction
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    # Learning and prediction
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    
    # Accuracy every cycle
    n_iter +=1
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} cross validation accuracy: {1}, train data size: {2}, test data size: {3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} validation set index: {1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
# cross validation accuracy and 평균 정확도 계산
print('\n## cross validation accuracy: ', np.round(cv_accuracy, 4))
print('## mean validation accuracy: ', np.round(np.mean(cv_accuracy), 4))


#1 cross validation accuracy: 1.0, train data size: 100, test data size: 50
#1 validation set index: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 cross validation accuracy: 1.0, train data size: 100, test data size: 50
#2 validation set index: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 cross validation accuracy: 0.98, train data size: 100, test data size: 50
#3 validation set index: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## cross validation accuracy:  [1.   1.   0.98]
## mean validation accuracy:  0.

## cross_val_score() p110

In [22]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# 성능 지표는 accuracy, cross valication set: 3
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('cross validation accuracy: ', np.round(scores, 4))
print('average valication accuracy: ', np.round(np.mean(scores), 4))

cross validation accuracy:  [0.98 0.94 0.98]
average valication accuracy:  0.9667
